name: lab0405
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/search.png
    - assets/icons/profile.png
    - assets/images/valorant.jpg
    - assets/images/fortnite.png
    - assets/images/overwatch.jpg
    - assets/images/thelastofus.jpg
    - assets/images/valorant_gameplay.jpg
